#ifndef EXEC_BUILTIN_H_INCLUDED
#define EXEC_BUILTIN_H_INCLUDED

#include "exec.h"

BUILTIN_FUNC(set);
BUILTIN_FUNC(print);
BUILTIN_FUNC(prints);
BUILTIN_FUNC(quote);
BUILTIN_FUNC(plus);
BUILTIN_FUNC(lambda);

#endif // EXEC_BUILTIN_H_INCLUDED
