#ifndef EXEC_BUILTIN_H_INCLUDED
#define EXEC_BUILTIN_H_INCLUDED

#include "exec.h"

BUILTIN_FUNC(def);
BUILTIN_FUNC(print);
BUILTIN_FUNC(quote);
BUILTIN_FUNC(plus);

#endif // EXEC_BUILTIN_H_INCLUDED
